POST http://localhost:8899/api/auth/login

###
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
#  "identity" : "andy@cc20.th",
 "identity" : "123456789099",
 "password" : "a1234"
}

###

# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#   "identity" : "1234567890",
 "identity" : "someone01@ggg.mail",
 "firstName" : "",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "12346"
}
###
POST http://localhost:8899/api/post HTTP/1.1
content-type: application/json

{
   "message": "sample"
}

