# Get Me
GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzgwNzI3NTU5LCJleHAiOjE3ODIwMjM1NTl9.TsG_g9NxwuiUqrUV-UMdXXxtUFKb9oifGr34_VlosCg


###


###
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
#  "identity" : "andy@ggg.mail",
 "identity" : "1111111111",
 "password" : "123456"
}

###

# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#   "identity" : "1234567890",
 "identity" : "andy@ggg.mail",
 "firstName" : "someone01",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###
POST http://localhost:8899/api/post HTTP/1.1
content-type: application/json

{
   "message": "sample"
}

